name: Build Release APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BiliTVNative-custom
          # 这段路径用了双星号 **，不管 APK 藏在 release 还是 debug 目录下，都能立刻抓出来
          path: app/build/outputs/apk/**/*.apk
